### ISSUE TITLE
Dans chapitre 10, question sur get_id()

### ISSUE THREAD

**Issue by alix-tz** [PonteIneptique/cours-python#12]
Bonjour, 

Dans le chapitre 10, vous avez écrit ceci (dans la partie dédiée à Flak-Login et UserMixin) : 
> Malheureusement, le get_id par défaut de UserMixin n'est pas complètement compatible avec notre User, car il a besoin d'une propriété .id pour que get_id() fonctionne.

Pourriez-vous expliquer en quoi consisterait une propriété .id et pourquoi nous ne l'avons pas dans le cas de notre application ? S'agit-il simplement d'une question de nom donné au champ qui contient la clef primaire ? Si c'est lié à l'utilisation d'une méthode statique, pourquoi ? 

Merci

**Comment by PonteIneptique** [comment]
Bonjour,
La fonction `User.get_id()` Flask Login attend en effet que notre utilisateur soit construit avec une propriété `User().id`. Dans notre cas, nous ne l'avons pas car : 
1. Aucun SQLAlchemy n'a été nommé ainsi
2. Nous n'avons pas écrit non plus notre propre propriété `.id`

Dans notre cas, l'équivalent de ce que rechercher FlaskLogin est donc `User().user_id`. Nous avons donc écrit par dessus la fonction `.get_id` afin que le problème se résolve.

Est-ce plus clair ?

**Comment by alix-tz** [comment]
C'est donc bien lié à la manière dont nous avons nommé le champ qui contient la clef primaire dans la table User ? Si on l'avait nommé "id", nous n'aurions pas ce problème. C'est bien cela ?

**Comment by PonteIneptique** [comment]
Tout à fait.

**Comment by alix-tz** [comment]
D'accord, alors c'est bon, j'ai compris !  
Merci
