### ISSUE TITLE
Disparition du python

### ISSUE THREAD

**Issue by Keyuteotter** [PonteIneptique/cours-python#16]
Bonjour, 

Juste pour signaler la disparition de notre chère mascotte Pythounou suite au cours de généalogie de mardi soir, au cas où quelqu'un l'ait vu ! 

Merci !

**Comment by algaudin** [comment]
![28170806_10215429584238682_1462695958_o](https://user-images.githubusercontent.com/33345655/36265739-2afbe8a2-1270-11e8-80d3-17470c7e1a6b.jpg)

**Comment by PonteIneptique** [comment]
Mon week-end est sauf.
